language: python
python:
- '3.5'
install:
- pip install pep8
script: python tests.py
notifications:
  pushover:
    api_key:
      secure: mDKhstP7idfaUjQa74Vj0XYQpjd5u2FVCe+pRmGktM+MJGUxa6m7CBuvVuy+XTAuv+ChdPw4hj96d5KGdwNngtmHQQIXd5yiSXCFJaHHJBFi4E/tJH6E/X1zSJoP5BYRdy6O2810c+DN3B5/pYQwko0j8B0k+xJJNEk1YdMgdTW2cCTSIucgcBselgkNKlnLaoOqQj/2r+hQ3BWOdGYdzexYr8UUnW+bjq0AgkQqvXzeEG3cbPK+vIc01HYe8tZ+uWJqLZpaLX6kmjutRCflOOiPDXQmymaXSWXB3am7pqMjE3beLNZyCMA3n3zF967qiMUTfMmOBDXWU/gHueiByl2bJTgKxAqXYQtEQSh7D9ci9L40QiMQ24mrY+yXHlPtNIuGQYUvSJDTJbn61m8BNLuu6eMoIWGNwENxSERe5/igHrcBE8t/KMPp6TH5adVA9N1nPR8DdKZLIuH8IrmOfdIjN/GoCqNARfS7g8d3gKJhUvRy815QccSPt3k1YjwmiyAHT3mRDtEojYL5fKxqX95byQq8ZMdwfvZt0YC+y6jOfhBQZPM3jSQjO/2i0kshwDq09Z29BOMYz0ZXCyt3xmUv3tFiIs4GBhxT3o+igtnKEVM4NGgFkN9t/dUUgXCBy0wMym0r/Bi1r3BEjw9Es8JTu31BJuC5+NiEjBJTAF4=
    users:
      secure: BcH6LIWbm3tc6MdBtgTR6BwwTYcjcZeDGimY+4ASq0IZiK1q5pfOovssuYdh0H5wxpxxg5wN9NQtFSmiRqQJHOJmr/HBs6WOEJkPv43XoLFquYyMel6ef0JMRXffBuyanoqf1894VXvttj1KFkUxbDyUX1VdIChPXT3AjXQ85B1o6s2diOqXdHbjXcMRAThA+Hc6OL6+QUWqfreTn43RGRh7PC4Qwc1BOz/FKV0u3qBGt+s81n+PmCQWWo+laM3AjWuPWdEQGYLUIEYt5MmZchpngYxOqhpSuPTAJ0QSdPOI4ksB4iMGpupDqiN9eWdMRxxUi1/XyQfYWOtcbPAglGNlIOsadirHYGAfdbIxmq5zNvTHo/ure3fSL6+2hJEN9MGnIQrKlSpAARZUuHdeO750RCD0sSBr3hpIF3w3NKudmRr/FdEGnKtvSl6r374vlLeYurbsNueaMfQBbJ9NgObkc7qu0q3VTeYmXC+pVZglGxK9TTESosraFRVR/hcXs/R2yczSnYKcoet8iUL09LeYs1B7HvGUZt03SgO2D0dCiuWZ84r0R8HFZUzyLzpxzXOOCFfl9h6gy2ZpebKhB/q4519XBaUfxcgPSHMRS4f6cTXHfjf6A9G7Rou13mc1wCWk710C7cFvB+BOoTPwoxzJe/gSqWQ21oOns4pgvBE=
